[project]
name = "tetris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.0.0",
    "numpy>=2.2.3",
    "ruff>=0.9.7",
    "tinygrad>=0.10.2",
]
